### ISSUE TITLE
stage 8 cosmomc "no active slurm jobs matching"

### ISSUE THREAD

**Issue by pmacias** [Samreay/Pippin#67] opened 2021-09-14 16:42 UTC
Hello,

In running my pippin job

cd /project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/pippin

pippin.sh -i 7 WFIRST_WIDE_ONLY.yml &

I am getting the following error in stage 8 which I can't really debug because no output is written in the stage 8 directory:

tail /scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_WIDE_ONLY/WFIRST_WIDE_ONLY.log

 A slightly modified set up worked previously, output here if that helps:

/scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_STARTERKIT+SETEXP

Thanks!!

- Phil

**Comment by OmegaLambda1998** [comment] 2021-09-14 23:25
Can you run this again with the verbose `-v` option? It will help me debug

**Comment by OmegaLambda1998** [comment] 2021-09-14 23:27
My instinct is that the issue is that you've commented out the `MASK_CREATE_COV` in the `COSMOMC` task. If possible, try with that uncommented

**Comment by OmegaLambda1998** [comment] 2021-09-17 01:39
@pmacias Just wondering if you got a change to rerun the task

**Comment by pmacias** [comment] 2021-09-20 16:38
@OmegaLambda1998 Hi Patrick, sorry for the delay! I don't think this did the trick..

I've uncommented the mask and re-run with the verbose flag, output is located here:

/scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_WIDE_ONLY/WFIRST_WIDE_ONLY.log

Thanks!

**Comment by OmegaLambda1998** [comment] 2021-09-20 22:59
Looks like it was a weird indentation bug. Not sure how that got passed testing, however it should be fixed up now!

**Comment by pmacias** [comment] 2021-09-21 17:15
Looks like it worked! Thanks Patrick!

**Closed** 2021-11-22 21:45 UTC
